[globalSettings]
check_interval_seconds = 60
timeout_seconds = 5

[[services]]
name = "google"
type = "http"
url = "https://google.com"
response_code = 200
check_interval_seconds = 30
timeout_seconds = 5
headers = [
    "User-Agent: Health-Check-Service"
]

[[services]]
name = "facebook"
type = "http"
url = "https://facebook.com"
response_code = 200
check_interval_seconds = 30
headers = [
    "User-Agent: Health-Check-Service"
]

[[services]]
name = "whatsapp"
type = "http"
url = "https://web.whatsapp.com"
response_code = 200
check_interval_seconds = 30
headers = [
    "User-Agent: Health-Check-Service"
]